### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by cdigruttola** [prestascan/prestascansecurity#14]
Hi,

I registered to the site, as shown in config page (green alert) but when I try to log in to start scan I receive the following error.
`{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}`
How can I use the module?

Thanks,
Carmine

**Comment by maxime-profileo** [comment]
Hi @cdigruttola 
Following a change in server side, the authentification following registration was broken.
This is now fixed ! You can download the new version from the https://github.com/prestascan/prestascansecurity/releases/tag/v1.1.1
Or from the direct download link : https://security.prestascan.com/prestashop
Let us know if this fixed the issue.
Don't forget to :star: the repo !
Cheers,
