### ISSUE TITLE
Prestascan indicates that a module has to be updated while i already have a newer version.

### ISSUE THREAD

**Issue by maniT4c** [prestascan/prestascansecurity#16]
With two of my modules Op'art Stat and Op'art Save cart, prestascan indicates that i have to do an update while i already have the lastest version.

For Op'art Save Cart it say that i have the 2.1.3 version while i have the 2.1.4 installed.
For Op'art stat it say that i havethe 2.0.0 version while i have the 2.0.12 installed.

**Comment by maxime-profileo** [comment]
Hello @maniT4c . Kindly send us the directory name used for these modules.

**Comment by maxime-profileo** [comment]
Hello @maniT4c 
We did not reproduce the issue. But based on your description it seems that it's the `getModuleList` function is returning a previous state of your modules' versions. Is it possible that you did not update these 2 modules from the classical BO way? It's possible that in your ps_module database you still have the old versions OR in your `config.xml` file.

**Comment by maxime-profileo** [comment]
Hello @maniT4c , we are closing this issue. Do not hesitate to open it again if you have more details to reproduce it.
