### ISSUE TITLE
whitelist prestascan

### ISSUE THREAD

**Issue by quasiperfect** [prestascan/prestascansecurity#32]
hi

can you provide an ip list (or other solution) to whitelist Prestascan behind an htaccess password ?

thanks

**Comment by Vincent-Profileo** [comment]
Hello,
Our requests are issued from the IP address:
87.98.153.45
If you whitelist this IP and when our server makes a call for a scan, it does not encounter BasicAuth authentication, then server to server communication will be fine.
Does this answer your question?
Best regards

**Comment by quasiperfect** [comment]
thanks @Vincent-Profileo
